import sanitizeHtmlModule from 'sanitize-html';

const ALLOWED_TAGS = [
  'address',
  'article',
  'aside',
  'blockquote',
  'div',
  'dl',
  'dt',
  'dd',
  'details',
  'summary',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'header',
  'hgroup',
  'main',
  'nav',
  'section',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'p',
  'pre',
  'hr',
  'ul',
  'ol',
  'li',
  'menu',
  'table',
  'caption',
  'colgroup',
  'col',
  'thead',
  'tbody',
  'tfoot',
  'tr',
  'td',
  'th',
  'a',
  'abbr',
  'b',
  'bdi',
  'bdo',
  'br',
  'cite',
  'code',
  'data',
  'dfn',
  'em',
  'i',
  'kbd',
  'mark',
  'q',
  'rb',
  'rp',
  'rt',
  'rtc',
  'ruby',
  's',
  'samp',
  'small',
  'span',
  'strong',
  'sub',
  'sup',
  'time',
  'u',
  'var',
  'wbr',
  'img',
  'picture',
  'source',
  'audio',
  'video',
  'track',
  'iframe',
];

const ALLOWED_ATTRIBUTES: NonNullable<
  Parameters<typeof sanitizeHtmlModule>[1]
>['allowedAttributes'] = {
  '*': [
    'id',
    'class',
    'style',
    'title',
    'lang',
    'dir',
    'align',
    'width',
    'height',
    'name',
    'value',
    'type',
  ],
  a: ['href', 'name', 'target', 'rel', 'title', 'download', 'hreflang'],
  img: [
    'src',
    'srcset',
    'sizes',
    'alt',
    'title',
    'width',
    'height',
    'loading',
    'decoding',
  ],
  iframe: [
    'src',
    'title',
    'width',
    'height',
    'allow',
    'allowfullscreen',
    'loading',
    'frameborder',
    'scrolling',
  ],
  video: [
    'src',
    'poster',
    'controls',
    'muted',
    'loop',
    'autoplay',
    'playsinline',
    'preload',
    'width',
    'height',
  ],
  audio: ['src', 'controls', 'muted', 'loop', 'autoplay', 'preload'],
  source: ['src', 'srcset', 'type', 'media', 'sizes'],
  track: ['src', 'kind', 'srclang', 'label', 'default'],
  th: [
    'colspan',
    'rowspan',
    'scope',
    'headers',
    'abbr',
    'align',
    'width',
    'height',
  ],
  td: ['colspan', 'rowspan', 'headers', 'align', 'width', 'height'],
  col: ['span', 'width', 'align'],
  colgroup: ['span', 'width', 'align'],
  ol: ['start', 'type', 'reversed'],
  li: ['value'],
  details: ['open'],
  time: ['datetime'],
  data: ['value'],
  blockquote: ['cite'],
  q: ['cite'],
  table: ['align', 'width', 'border', 'cellpadding', 'cellspacing', 'summary'],
};

export function sanitizeHtml(dirty: string): string {
  return sanitizeHtmlModule(dirty, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: ALLOWED_ATTRIBUTES,
    allowedSchemes: ['http', 'https', 'ftp', 'mailto', 'tel', 'data'],
    allowedSchemesByTag: {
      img: ['data'],
      source: ['data'],
      video: ['data'],
      audio: ['data'],
    },
    allowProtocolRelative: true,
    parseStyleAttributes: false,
    disallowedTagsMode: 'discard',
  });
}

export default sanitizeHtml;
