import type { AiSpecEntry } from '#logic/types/AiSpec';

export const galleryAiSpec: AiSpecEntry = {
  name: 'gallery',
  icon: 'gallery-fill',
  aiSpec: {
    brief:
      'Collection of media items (images, videos). Use for character portraits, concept art, screenshots, or any visual media collection.',
    spec: 'Each item is keyed by an opaque key and stored as:\n- `{key}\\type` — media type string: "file" (uploaded file), "youtube", "extimage", "extvideo", "rutube", "vkvideo"\n- `{key}\\value` — the media data. For type "file": AssetPropValueFile with `FileId`, `Title`, `Size`, `Dir`, `Store`. For external types: a string URL.\n- `{key}\\title` — caption shown under the item (string, optional)\n- `{key}\\inherited` — whether the item is inherited from a parent (boolean, optional)\n\nItem ordering and slot metadata live under the reserved `__slots\\{key}\\` namespace:\n- `__slots\\{key}\\index` — sort order (number)\n- `__slots\\{key}\\name` — service name of the item (string, optional). When present, the item is a named slot and `{key}` MUST equal `name` normalized to a prop key part (lowercased, backslash and brackets removed, whitespace/underscores collapsed to single `_`, numeric-only names prefixed with `_`, and `name` itself is the unnormalized original).\n\nA slot may be empty: it has `__slots\\{key}\\name` and `__slots\\{key}\\index` but no `{key}\\type` and no `{key}\\value`. Such items render as an empty placeholder and are ignored by viewers, so do not create empty slots unless a placeholder is really needed. Items without a name keep an arbitrary key (a uuid is recommended).\n\nBackward compatibility: legacy data may store `{key}\\index` and `{key}\\name` inside the item payload instead of `__slots\\{key}\\...`. Keep reading those as a fallback; do not rewrite them unless the item is reordered. An empty slot is stored as a bare `{key}: null` prop (a null AssetPropValue) instead of having no payload keys at all.\n\nExample (character concept art gallery with one named slot and one plain item):\n{\n  "a1b2c3d4-...\\\\type": "file",\n  "a1b2c3d4-...\\\\value": { "FileId": "a1b2c3d4-...", "Title": "hero_concept_front.png", "Size": 124567, "Dir": "concepts", "Store": "p-abc123" },\n  "e5f6g7h8-...\\\\type": "file",\n  "e5f6g7h8-...\\\\value": { "FileId": "e5f6g7h8-...", "Title": "hero_concept_back.png", "Size": 112345, "Dir": "concepts", "Store": "p-abc123" },\n  "i9j0k1l2-...\\\\type": "youtube",\n  "i9j0k1l2-...\\\\value": "https://www.youtube.com/watch?v=example",\n  "__slots\\\\a1b2c3d4-...\\\\index": 1,\n  "__slots\\\\e5f6g7h8-...\\\\index": 2,\n  "__slots\\\\i9j0k1l2-...\\\\index": 3,\n  "portrait\\\\type": "extimage",\n  "portrait\\\\value": "https://example.com/portrait.png",\n  "__slots\\\\portrait\\\\index": 4,\n  "__slots\\\\portrait\\\\name": "portrait",\n  "banner\\\\type": "file",\n  "banner\\\\value": { "FileId": "banner-file-...", "Title": "banner.png", "Size": 99890, "Dir": "concepts", "Store": "p-abc123" },\n  "__slots\\\\banner\\\\index": 5,\n  "__slots\\\\banner\\\\name": "banner"\n}',
    needSpec: true,
  },
};
